### ISSUE TITLE
[Proposal] Path to RC1

### ISSUE THREAD

**Issue by rtablada** [Appyre/driven#3]
There's a lot currently dreamed about for Driven, I think it's time to take back and look at what can be accomplished and what is needed under the hood.
This will be a todo list toward RC1 and will link to further discussion for topics and APIs that need to be settled on where these issues exist.

Svelte refactors of `driven` and `driven-cli` will be on each `jj-abrams` branch.

> **NOTE** RC 1 does not include web socket support

IMO the `driven-api` package is fairly small, and addons will provide functionality beyond this core set:
- Application Container
- Service Providers (or whatever naming make sense) to allow addons and end users to register items with the application container and work with module groups
- Actions - Promise driven middleware abstraction
- Routing - Registers actions to express or connect routes
## Todos

This list will likely include items shared between `driven-api` and `driven-cli`:
- [x] `driven new` and `driven init` commands
- [ ] `driven serve`
  - [ ] Compile server code into Node.js compatible code
  - [ ] Restart server child process on rebuild
  - [ ] Restart server child process on errors
- [ ] `driven build` ??? What's the build target?
- [ ] `driven g`
  - [ ] `driven g route <HTTP METHOD> <URL> <ACTION MODULE NAME>`
  - [ ] `driven g action <ACTION MODULE NAME>`
  - [ ] `driven g action-decorator [--before] [--after] <DECORATOR NAME>`
- [ ] Decorators
  - [ ] Abstraction for writing creating decorators
  - [ ] `@middlwareDecorator(middlewarefunction)` for interop with existing Express middleware
- [ ] Application Container
  - [ ] Module lookup
  - [ ] Namespace lookup
  - [ ] `app.register` - registers a singleton to be used when a module is looked up with `app.make`
  - [ ] `app.make` - looks up a singleton or runs `new` on a looked up module
  - [ ] `app.config` - pulls in configuration from `config/environment.js`
- [ ] Provider
  - [ ] `boot` hook - allows addon authors to lookup items from application container and register new items
  - [ ] `modulesForNameSpace` method - Returns an array of modules in a namespace that can be looped over (for instance for model auto registration)
    `[ ]`this.app` - reference to app container instance
- [ ] Services
  - Services are similar to Ember services and are available to look up using `app.service(serviceName)`
- [ ] Actions & Middleware
  - [ ] `Action` Class
    - [x] Promise aware `handle` hook
    - [x] Promise aware `beforeAll`, `before`, `after`, `afterAll` hooks
    - [x] Decorator registered `beforeHooks` and `afterHooks` (allows for things like serialization, model decoration, etc)
    - [ ] Error hooks
    - [ ] Ability to stop the standard flow (ex. returning validation response)
    - [ ] Ability to get `req` from raw middleware
    - [ ] Ability to get `res` from raw middleware
    - [ ] Ability to get `next` from raw middleware
  - [ ] `MiddlewareResponse` Class
    - `new MiddlewareResponse(action, function(req, res, next) { /* Do work here */})`
  - [ ] Decorator for working with existing Express/Connect middleware
- [ ] Router
  - [x] `get`, `post`, `put`, `patch`, `delete`, etc support
  - [x] Resource groups - https://github.com/rtablada/driven-scratchpad/blob/master/src/index.js#L34
  - [ ] Action registration `router.get('users', 'users.all')` or `router.get('users', {module: 'users.all'})`
  - [ ] Turn registered actions into express routes
  - [ ] Coalesce requests (similar to current `/view` proposal in README)
- [ ] Addons
  - [ ] Addon Blueprint
  - [ ] `includeProviders` config to allow registering which providers are loaded (maybe in `index.js`)
  - [ ] `driven g provider` - Generate a new provider and register with `includedProviders` array

---

Some common features such as ORMs and Serialization will be addons (some of them first party).
This serves two purposes
- One allow users to swap out ORMs or other services
- Test addon functionality

I foresee at least for my use that `driven-knex` and `driven-json-api-decorators` will be worked on in tandem with RC1

**Comment by rtablada** [comment]
@runspired anything you see missing or something that should be addonified?
